apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-workflow-pv
  namespace: qgnet
spec:
  capacity:
    storage: 5Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Allows multiple nodes to write
  hostPath:
    path: /rancher-pv-argo-helm/  # Adjust to the path you want on your host machine
